const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', '..', 'データ', '分析結果JSON');
const OUTPUT_DIR = path.join(__dirname, '..', '..', 'ホームページ');

// Read portfolio data
const portfolio = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'primechange_portfolio_analysis.json'), 'utf8'));

// Read all hotel analysis JSONs
const hotelFiles = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('_analysis.json') && !f.includes('portfolio'));
const hotels = {};
for (const file of hotelFiles) {
  const key = file.replace('_analysis.json', '');
  const data = JSON.parse(fs.readFileSync(path.join(DATA_DIR, file), 'utf8'));
  hotels[key] = data;
}

// Build hotel detail data (limit comments for page size)
const hotelDetails = {};
for (const [key, data] of Object.entries(hotels)) {
  hotelDetails[key] = {
    total_reviews: data.total_reviews,
    overall_avg_10pt: data.overall_avg_10pt,
    high_count: data.high_count,
    high_rate: data.high_rate,
    mid_count: data.mid_count,
    mid_rate: data.mid_rate,
    low_count: data.low_count,
    low_rate: data.low_rate,
    site_stats: data.site_stats,
    distribution: data.distribution,
    comments: (data.comments || []).slice(0, 30).map(c => ({
      site: c.site,
      rating_10pt: c.rating_10pt,
      date: c.date,
      comment: (c.translated || c.comment || '').slice(0, 300),
      good: (c.translated_good || c.good || '').slice(0, 200),
      bad: (c.translated_bad || c.bad || '').slice(0, 200),
    }))
  };
}

const tierColor = { '優秀': '#10B981', '良好': '#3B82F6', '概ね良好': '#F59E0B', '要改善': '#EF4444' };
const priorityLabel = { 'MAINTENANCE': '維持', 'STANDARD': '標準', 'HIGH': '要注意', 'URGENT': '緊急' };
const priorityColor = { 'MAINTENANCE': '#10B981', 'STANDARD': '#6B7280', 'HIGH': '#F59E0B', 'URGENT': '#EF4444' };

// Escape for HTML
function esc(s) {
  return String(s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
}

// Build hotel cards HTML
function buildHotelCards() {
  return portfolio.portfolio_overview.hotels_ranked.map(function(h) {
    var tc = tierColor[h.tier];
    var pc = priorityColor[h.priority];
    var pl = priorityLabel[h.priority];
    var barPct = (h.avg / 10 * 100).toFixed(0);
    var rankBg = h.rank <= 3 ? '#F59E0B' : h.rank <= 10 ? '#3B82F6' : '#94A3B8';
    var detail = hotelDetails[h.key] || {};
    var sites = (detail.site_stats || []).map(function(s) {
      return '<span class="site-dot">' + esc(s.site) + ' ' + s.avg_10pt + '</span>';
    }).join('');
    var cleanColor = h.cleaning_issue_rate > 5 ? 'var(--red)' : h.cleaning_issue_rate > 0 ? 'var(--orange)' : 'var(--green)';

    return [
      '<div class="hotel-card" data-tier="' + esc(h.tier) + '" data-key="' + esc(h.key) + '" data-name="' + esc(h.name) + '" data-rank="' + h.rank + '" data-reviews="' + h.total_reviews + '" data-high-rate="' + h.high_rate + '" data-low-rate="' + h.low_rate + '" data-cleaning="' + h.cleaning_issue_rate + '" onclick="openModal(\'' + esc(h.key) + '\')">',
      '  <div class="hotel-card-header">',
      '    <h3>' + esc(h.name) + '</h3>',
      '    <div class="rank-badge" style="background:' + rankBg + ';">' + h.rank + '</div>',
      '  </div>',
      '  <div class="hotel-card-body">',
      '    <div class="score-row">',
      '      <div class="score-big" style="color:' + tc + ';">' + h.avg + '</div>',
      '      <div class="score-bar-wrap">',
      '        <div class="score-bar-bg"><div class="score-bar" style="width:' + barPct + '%;background:' + tc + ';"></div></div>',
      '        <div class="score-label" style="display:flex;justify-content:space-between;">',
      '          <span><span class="tier-badge" style="background:' + tc + ';">' + esc(h.tier) + '</span><span class="priority-badge" style="background:' + pc + ';">' + pl + '</span></span>',
      '          <span>' + h.total_reviews + '件</span>',
      '        </div>',
      '      </div>',
      '    </div>',
      '    <div class="stats-row">',
      '      <div class="stat-chip"><div class="val" style="color:var(--green);">' + h.high_rate + '%</div><div class="lbl">高評価</div></div>',
      '      <div class="stat-chip"><div class="val" style="color:var(--red);">' + h.low_rate + '%</div><div class="lbl">低評価</div></div>',
      '      <div class="stat-chip"><div class="val" style="color:' + cleanColor + ';">' + h.cleaning_issue_rate + '%</div><div class="lbl">清掃課題</div></div>',
      '    </div>',
      '    <div class="site-dots">' + sites + '</div>',
      '  </div>',
      '</div>'
    ].join('\n');
  }).join('\n');
}

var meta = portfolio.report_metadata;
var pov = portfolio.portfolio_overview;

var html = [
'<!DOCTYPE html>',
'<html lang="ja">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'<title>PRIMECHANGE ホテル口コミ分析ダッシュボード</title>',
'<style>',
'  :root { --navy: #0F172A; --navy-light: #1E293B; --accent: #3B82F6; --accent-light: #60A5FA; --bg: #F8FAFC; --card: #FFFFFF; --text: #1E293B; --text-light: #64748B; --border: #E2E8F0; --green: #10B981; --blue: #3B82F6; --orange: #F59E0B; --red: #EF4444; --radius: 12px; --shadow: 0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06); --shadow-lg: 0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px rgba(0,0,0,0.05); }',
'  * { margin: 0; padding: 0; box-sizing: border-box; }',
'  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Kaku Gothic ProN", "Noto Sans JP", sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; }',
'  .header { background: linear-gradient(135deg, var(--navy) 0%, #1E3A5F 100%); color: white; padding: 1.5rem 0; position: sticky; top: 0; z-index: 100; box-shadow: var(--shadow-lg); }',
'  .header-inner { max-width: 1400px; margin: 0 auto; padding: 0 2rem; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem; }',
'  .header h1 { font-size: 1.4rem; font-weight: 700; letter-spacing: 0.05em; }',
'  .header .subtitle { font-size: 0.8rem; color: #94A3B8; margin-top: 0.2rem; }',
'  .header-meta { text-align: right; font-size: 0.75rem; color: #94A3B8; }',
'  .header-meta span { color: white; font-weight: 600; }',
'  .container { max-width: 1400px; margin: 0 auto; padding: 2rem; }',
'  .kpi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }',
'  .kpi-card { background: var(--card); border-radius: var(--radius); padding: 1.25rem 1.5rem; box-shadow: var(--shadow); border-left: 4px solid var(--accent); }',
'  .kpi-label { font-size: 0.7rem; color: var(--text-light); text-transform: uppercase; letter-spacing: 0.05em; font-weight: 600; }',
'  .kpi-value { font-size: 2rem; font-weight: 800; color: var(--navy); margin: 0.25rem 0; }',
'  .kpi-sub { font-size: 0.8rem; color: var(--text-light); }',
'  .filter-bar { background: var(--card); border-radius: var(--radius); padding: 1rem 1.5rem; box-shadow: var(--shadow); margin-bottom: 1.5rem; display: flex; gap: 0.75rem; flex-wrap: wrap; align-items: center; }',
'  .filter-bar label { font-size: 0.8rem; font-weight: 600; color: var(--text-light); }',
'  .filter-btn { padding: 0.4rem 1rem; border-radius: 20px; border: 1.5px solid var(--border); background: white; cursor: pointer; font-size: 0.8rem; font-weight: 500; transition: all 0.2s; }',
'  .filter-btn:hover { border-color: var(--accent); color: var(--accent); }',
'  .filter-btn.active { background: var(--accent); color: white; border-color: var(--accent); }',
'  .search-input { padding: 0.4rem 1rem; border-radius: 20px; border: 1.5px solid var(--border); font-size: 0.85rem; width: 220px; outline: none; transition: border-color 0.2s; }',
'  .search-input:focus { border-color: var(--accent); }',
'  .sort-select { padding: 0.4rem 1rem; border-radius: 20px; border: 1.5px solid var(--border); font-size: 0.8rem; background: white; cursor: pointer; outline: none; }',
'  .hotel-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(340px, 1fr)); gap: 1.25rem; margin-bottom: 2rem; }',
'  .hotel-card { background: var(--card); border-radius: var(--radius); box-shadow: var(--shadow); overflow: hidden; cursor: pointer; transition: transform 0.2s, box-shadow 0.2s; }',
'  .hotel-card:hover { transform: translateY(-3px); box-shadow: var(--shadow-lg); }',
'  .hotel-card-header { padding: 1.25rem 1.5rem 0.75rem; display: flex; justify-content: space-between; align-items: flex-start; }',
'  .hotel-card-header h3 { font-size: 0.95rem; font-weight: 700; line-height: 1.4; flex: 1; }',
'  .rank-badge { width: 32px; height: 32px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 0.75rem; font-weight: 800; color: white; flex-shrink: 0; margin-left: 0.75rem; }',
'  .hotel-card-body { padding: 0 1.5rem 1.25rem; }',
'  .score-row { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.75rem; }',
'  .score-big { font-size: 2rem; font-weight: 800; }',
'  .score-bar-wrap { flex: 1; }',
'  .score-bar-bg { height: 8px; background: #E2E8F0; border-radius: 4px; overflow: hidden; }',
'  .score-bar { height: 100%; border-radius: 4px; transition: width 0.6s ease; }',
'  .score-label { font-size: 0.7rem; color: var(--text-light); margin-top: 2px; }',
'  .tier-badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.7rem; font-weight: 700; color: white; }',
'  .priority-badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.65rem; font-weight: 600; color: white; margin-left: 0.4rem; }',
'  .stats-row { display: flex; gap: 0.5rem; margin-top: 0.75rem; }',
'  .stat-chip { flex: 1; text-align: center; padding: 0.4rem; border-radius: 6px; background: #F1F5F9; }',
'  .stat-chip .val { font-size: 0.95rem; font-weight: 700; }',
'  .stat-chip .lbl { font-size: 0.6rem; color: var(--text-light); }',
'  .site-dots { display: flex; gap: 0.25rem; margin-top: 0.75rem; flex-wrap: wrap; }',
'  .site-dot { font-size: 0.65rem; padding: 0.15rem 0.5rem; border-radius: 10px; background: #F1F5F9; color: var(--text-light); white-space: nowrap; }',
'  .modal-overlay { display: none; position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.5); z-index: 200; justify-content: center; align-items: flex-start; padding: 2rem; overflow-y: auto; }',
'  .modal-overlay.active { display: flex; }',
'  .modal { background: var(--card); border-radius: var(--radius); max-width: 900px; width: 100%; box-shadow: var(--shadow-lg); animation: slideUp 0.3s ease; }',
'  @keyframes slideUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }',
'  .modal-header { padding: 1.5rem 2rem; border-bottom: 1px solid var(--border); display: flex; justify-content: space-between; align-items: center; }',
'  .modal-header h2 { font-size: 1.25rem; font-weight: 700; }',
'  .modal-close { width: 36px; height: 36px; border-radius: 50%; border: none; background: #F1F5F9; cursor: pointer; font-size: 1.2rem; display: flex; align-items: center; justify-content: center; transition: background 0.2s; }',
'  .modal-close:hover { background: #E2E8F0; }',
'  .modal-body { padding: 2rem; }',
'  .section-title { font-size: 0.9rem; font-weight: 700; color: var(--navy); margin: 1.5rem 0 0.75rem; padding-bottom: 0.5rem; border-bottom: 2px solid var(--accent); }',
'  .section-title:first-child { margin-top: 0; }',
'  .site-table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }',
'  .site-table th { background: #F8FAFC; padding: 0.6rem 0.75rem; text-align: left; font-weight: 600; color: var(--text-light); font-size: 0.75rem; }',
'  .site-table td { padding: 0.6rem 0.75rem; border-top: 1px solid var(--border); }',
'  .site-table tr:hover td { background: #F8FAFC; }',
'  .dist-chart { display: flex; align-items: flex-end; gap: 4px; height: 120px; padding: 0.5rem 0; }',
'  .dist-bar-wrap { flex: 1; display: flex; flex-direction: column; align-items: center; height: 100%; justify-content: flex-end; }',
'  .dist-bar { width: 100%; min-width: 20px; border-radius: 4px 4px 0 0; }',
'  .dist-label { font-size: 0.65rem; color: var(--text-light); margin-top: 4px; }',
'  .dist-pct { font-size: 0.6rem; font-weight: 600; margin-bottom: 2px; }',
'  .rate-bars { display: flex; gap: 1rem; flex-direction: column; }',
'  .rate-bar-item { }',
'  .rate-bar-header { display: flex; justify-content: space-between; margin-bottom: 4px; }',
'  .rate-bar-label { font-size: 0.75rem; font-weight: 600; }',
'  .rate-bar-val { font-size: 0.75rem; font-weight: 700; }',
'  .rate-bar-track { height: 10px; background: #E2E8F0; border-radius: 5px; overflow: hidden; }',
'  .rate-bar-fill { height: 100%; border-radius: 5px; }',
'  .review-list { display: flex; flex-direction: column; gap: 0.75rem; max-height: 500px; overflow-y: auto; }',
'  .review-card { padding: 1rem; border-radius: 8px; background: #F8FAFC; border-left: 3px solid var(--border); }',
'  .review-card.high { border-left-color: var(--green); }',
'  .review-card.mid { border-left-color: var(--orange); }',
'  .review-card.low { border-left-color: var(--red); }',
'  .review-meta { display: flex; gap: 0.75rem; align-items: center; margin-bottom: 0.5rem; flex-wrap: wrap; }',
'  .review-site { font-size: 0.7rem; padding: 0.15rem 0.5rem; border-radius: 4px; background: var(--navy); color: white; font-weight: 600; }',
'  .review-score { font-size: 0.8rem; font-weight: 700; }',
'  .review-date { font-size: 0.7rem; color: var(--text-light); }',
'  .review-text { font-size: 0.8rem; line-height: 1.7; color: var(--text); }',
'  .review-good { color: var(--green); }',
'  .review-bad { color: var(--red); }',
'  .footer { text-align: center; padding: 2rem; color: var(--text-light); font-size: 0.75rem; border-top: 1px solid var(--border); margin-top: 2rem; }',
'  @media (max-width: 768px) {',
'    .container { padding: 1rem; }',
'    .hotel-grid { grid-template-columns: 1fr; }',
'    .kpi-grid { grid-template-columns: repeat(2, 1fr); }',
'    .header-inner { flex-direction: column; text-align: center; }',
'    .header-meta { text-align: center; }',
'    .filter-bar { flex-direction: column; align-items: stretch; }',
'    .search-input { width: 100%; }',
'    .modal { margin: 1rem; }',
'    .modal-body { padding: 1rem; }',
'  }',
'</style>',
'</head>',
'<body>',
'',
'<div class="header">',
'  <div class="header-inner">',
'    <div>',
'      <h1>PRIMECHANGE ホテル口コミ分析ダッシュボード</h1>',
'      <div class="subtitle">ゲスト口コミデータに基づく清掃品質分析・改善提案</div>',
'    </div>',
'    <div class="header-meta">',
'      <div>分析期間: <span>' + meta.analysis_period + '</span></div>',
'      <div>最終更新: <span>' + meta.date + '</span></div>',
'    </div>',
'  </div>',
'</div>',
'',
'<div class="container">',
'  <div class="kpi-grid">',
'    <div class="kpi-card" style="border-left-color: var(--accent);">',
'      <div class="kpi-label">管理ホテル数</div>',
'      <div class="kpi-value">' + meta.total_hotels + '</div>',
'      <div class="kpi-sub">ホテル</div>',
'    </div>',
'    <div class="kpi-card" style="border-left-color: var(--green);">',
'      <div class="kpi-label">総口コミ数</div>',
'      <div class="kpi-value">' + meta.total_reviews.toLocaleString() + '</div>',
'      <div class="kpi-sub">件の口コミを分析</div>',
'    </div>',
'    <div class="kpi-card" style="border-left-color: ' + (pov.avg_score >= 8 ? 'var(--green)' : 'var(--orange)') + ';">',
'      <div class="kpi-label">ポートフォリオ平均</div>',
'      <div class="kpi-value">' + pov.avg_score + '</div>',
'      <div class="kpi-sub">/ 10 点</div>',
'    </div>',
'    <div class="kpi-card" style="border-left-color: var(--green);">',
'      <div class="kpi-label">高評価率</div>',
'      <div class="kpi-value">' + pov.portfolio_high_rate + '%</div>',
'      <div class="kpi-sub">8点以上の割合</div>',
'    </div>',
'    <div class="kpi-card" style="border-left-color: var(--red);">',
'      <div class="kpi-label">低評価率</div>',
'      <div class="kpi-value">' + pov.portfolio_low_rate + '%</div>',
'      <div class="kpi-sub">4点以下の割合</div>',
'    </div>',
'  </div>',
'',
'  <div class="filter-bar">',
'    <label>絞り込み:</label>',
'    <button class="filter-btn active" data-filter="all">すべて (' + pov.hotels_ranked.length + ')</button>',
'    <button class="filter-btn" data-filter="優秀">優秀</button>',
'    <button class="filter-btn" data-filter="良好">良好</button>',
'    <button class="filter-btn" data-filter="概ね良好">概ね良好</button>',
'    <button class="filter-btn" data-filter="要改善">要改善</button>',
'    <div style="flex:1;"></div>',
'    <label>並び替え:</label>',
'    <select class="sort-select" id="sortSelect">',
'      <option value="rank">ランキング順</option>',
'      <option value="reviews">口コミ数順</option>',
'      <option value="high_rate">高評価率順</option>',
'      <option value="low_rate">低評価率順</option>',
'      <option value="cleaning">清掃課題率順</option>',
'    </select>',
'    <input type="text" class="search-input" placeholder="ホテル名で検索..." id="searchInput">',
'  </div>',
'',
'  <div class="hotel-grid" id="hotelGrid">',
buildHotelCards(),
'  </div>',
'</div>',
'',
'<div class="modal-overlay" id="modalOverlay" onclick="if(event.target===this)closeModal();">',
'  <div class="modal">',
'    <div class="modal-header">',
'      <h2 id="modalTitle"></h2>',
'      <button class="modal-close" onclick="closeModal();">&#10005;</button>',
'    </div>',
'    <div class="modal-body" id="modalBody"></div>',
'  </div>',
'</div>',
'',
'<div class="footer">',
'  &copy; 2026 PRIMECHANGE ホテル口コミ分析システム &mdash; Confidential',
'</div>',
'',
'<script>',
'var hotelDetails = ' + JSON.stringify(hotelDetails) + ';',
'var hotelRanked = ' + JSON.stringify(pov.hotels_ranked) + ';',
'var tierColor = ' + JSON.stringify(tierColor) + ';',
'',
'document.querySelectorAll(".filter-btn").forEach(function(btn) {',
'  btn.addEventListener("click", function() {',
'    document.querySelectorAll(".filter-btn").forEach(function(b) { b.classList.remove("active"); });',
'    btn.classList.add("active");',
'    applyFilters();',
'  });',
'});',
'document.getElementById("searchInput").addEventListener("input", applyFilters);',
'document.getElementById("sortSelect").addEventListener("change", function() { sortCards(); applyFilters(); });',
'',
'function applyFilters() {',
'  var filter = document.querySelector(".filter-btn.active").dataset.filter;',
'  var search = document.getElementById("searchInput").value.toLowerCase();',
'  document.querySelectorAll(".hotel-card").forEach(function(card) {',
'    var tier = card.dataset.tier;',
'    var name = card.dataset.name.toLowerCase();',
'    var show = (filter === "all" || tier === filter) && (!search || name.includes(search));',
'    card.style.display = show ? "" : "none";',
'  });',
'}',
'',
'function sortCards() {',
'  var sort = document.getElementById("sortSelect").value;',
'  var grid = document.getElementById("hotelGrid");',
'  var cards = Array.from(grid.children);',
'  cards.sort(function(a, b) {',
'    if (sort === "rank") return +a.dataset.rank - +b.dataset.rank;',
'    if (sort === "reviews") return +b.dataset.reviews - +a.dataset.reviews;',
'    if (sort === "high_rate") return +b.dataset.highRate - +a.dataset.highRate;',
'    if (sort === "low_rate") return +b.dataset.lowRate - +a.dataset.lowRate;',
'    if (sort === "cleaning") return +b.dataset.cleaning - +a.dataset.cleaning;',
'    return 0;',
'  });',
'  cards.forEach(function(c) { grid.appendChild(c); });',
'}',
'',
'function escHtml(s) { var d = document.createElement("div"); d.textContent = s; return d.innerHTML; }',
'',
'function openModal(key) {',
'  var info = hotelRanked.find(function(h) { return h.key === key; });',
'  var detail = hotelDetails[key];',
'  if (!info || !detail) return;',
'',
'  document.getElementById("modalTitle").textContent = info.name;',
'  var tc = tierColor[info.tier];',
'',
'  var siteRows = (detail.site_stats || []).map(function(s) {',
'    var jc = tierColor[s.judgment] || "#6B7280";',
'    return "<tr><td><strong>" + escHtml(s.site) + "</strong></td><td>" + s.count + "件</td><td>" + s.native_avg + " (" + escHtml(s.scale) + ")</td><td><strong>" + s.avg_10pt + "</strong></td><td><span style=\\"color:" + jc + ";font-weight:700;\\">" + escHtml(s.judgment) + "</span></td></tr>";',
'  }).join("");',
'',
'  var allScores = [10,9,8,7,6,5,4,3,2,1];',
'  var distMap = {};',
'  (detail.distribution || []).forEach(function(d) { distMap[d.score] = d; });',
'  var maxCount = Math.max.apply(null, (detail.distribution || []).map(function(d) { return d.count; }).concat([1]));',
'  var distBars = allScores.map(function(score) {',
'    var d = distMap[score] || {count:0, pct:"0%"};',
'    var h = (d.count / maxCount * 100).toFixed(0);',
'    var color = score >= 8 ? "var(--green)" : score >= 5 ? "var(--orange)" : "var(--red)";',
'    return "<div class=\\"dist-bar-wrap\\"><div class=\\"dist-pct\\">" + (d.count > 0 ? d.count : "") + "</div><div class=\\"dist-bar\\" style=\\"height:" + Math.max(h, 2) + "%;background:" + color + ";\\"></div><div class=\\"dist-label\\">" + score + "</div></div>";',
'  }).join("");',
'',
'  var reviewCards = (detail.comments || []).map(function(c) {',
'    var cls = c.rating_10pt >= 8 ? "high" : c.rating_10pt >= 5 ? "mid" : "low";',
'    var sc = c.rating_10pt >= 8 ? "var(--green)" : c.rating_10pt >= 5 ? "var(--orange)" : "var(--red)";',
'    var text = "";',
'    if (c.good || c.bad) {',
'      if (c.good) text += "<span class=\\"review-good\\">&#128077; " + escHtml(c.good) + "</span><br>";',
'      if (c.bad) text += "<span class=\\"review-bad\\">&#128078; " + escHtml(c.bad) + "</span>";',
'    } else {',
'      text = escHtml(c.comment || "");',
'    }',
'    return "<div class=\\"review-card " + cls + "\\"><div class=\\"review-meta\\"><span class=\\"review-site\\">" + escHtml(c.site) + "</span><span class=\\"review-score\\" style=\\"color:" + sc + ";\\">" + c.rating_10pt + "点</span><span class=\\"review-date\\">" + escHtml(c.date || "") + "</span></div><div class=\\"review-text\\">" + text + "</div></div>";',
'  }).join("");',
'',
'  document.getElementById("modalBody").innerHTML = ',
'    "<div style=\\"display:flex;gap:1.5rem;flex-wrap:wrap;margin-bottom:1rem;\\">" +',
'    "  <div style=\\"text-align:center;\\">" +',
'    "    <div style=\\"font-size:3rem;font-weight:800;color:" + tc + ";\\">" + detail.overall_avg_10pt + "</div>" +',
'    "    <div style=\\"font-size:0.8rem;color:var(--text-light);\\">/ 10 点</div>" +',
'    "    <span class=\\"tier-badge\\" style=\\"background:" + tc + ";margin-top:0.5rem;\\">" + escHtml(info.tier) + "</span>" +',
'    "  </div>" +',
'    "  <div class=\\"rate-bars\\" style=\\"flex:1;min-width:250px;\\">" +',
'    "    <div class=\\"rate-bar-item\\"><div class=\\"rate-bar-header\\"><span class=\\"rate-bar-label\\" style=\\"color:var(--green);\\">高評価 (8-10)</span><span class=\\"rate-bar-val\\">" + detail.high_rate + "% (" + detail.high_count + "件)</span></div><div class=\\"rate-bar-track\\"><div class=\\"rate-bar-fill\\" style=\\"width:" + detail.high_rate + "%;background:var(--green);\\"></div></div></div>" +',
'    "    <div class=\\"rate-bar-item\\"><div class=\\"rate-bar-header\\"><span class=\\"rate-bar-label\\" style=\\"color:var(--orange);\\">中評価 (5-7)</span><span class=\\"rate-bar-val\\">" + detail.mid_rate + "% (" + detail.mid_count + "件)</span></div><div class=\\"rate-bar-track\\"><div class=\\"rate-bar-fill\\" style=\\"width:" + detail.mid_rate + "%;background:var(--orange);\\"></div></div></div>" +',
'    "    <div class=\\"rate-bar-item\\"><div class=\\"rate-bar-header\\"><span class=\\"rate-bar-label\\" style=\\"color:var(--red);\\">低評価 (1-4)</span><span class=\\"rate-bar-val\\">" + detail.low_rate + "% (" + detail.low_count + "件)</span></div><div class=\\"rate-bar-track\\"><div class=\\"rate-bar-fill\\" style=\\"width:" + detail.low_rate + "%;background:var(--red);\\"></div></div></div>" +',
'    "  </div>" +',
'    "</div>" +',
'    "<div class=\\"section-title\\">&#128202; スコア分布</div>" +',
'    "<div class=\\"dist-chart\\">" + distBars + "</div>" +',
'    "<div class=\\"section-title\\">&#127760; サイト別評価</div>" +',
'    "<table class=\\"site-table\\"><thead><tr><th>サイト</th><th>件数</th><th>元スコア</th><th>10点換算</th><th>判定</th></tr></thead><tbody>" + siteRows + "</tbody></table>" +',
'    "<div class=\\"section-title\\">&#128172; 口コミ一覧 (最大30件)</div>" +',
'    "<div class=\\"review-list\\">" + (reviewCards || "<p style=\\"color:var(--text-light);font-size:0.85rem;\\">口コミデータがありません</p>") + "</div>";',
'',
'  document.getElementById("modalOverlay").classList.add("active");',
'  document.body.style.overflow = "hidden";',
'}',
'',
'function closeModal() {',
'  document.getElementById("modalOverlay").classList.remove("active");',
'  document.body.style.overflow = "";',
'}',
'document.addEventListener("keydown", function(e) { if (e.key === "Escape") closeModal(); });',
'</script>',
'</body>',
'</html>'
].join('\n');

// Write output
if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUTPUT_DIR, 'index.html'), html, 'utf8');
console.log('Done: ' + path.join(OUTPUT_DIR, 'index.html'));
